version: '3.8'

services:
  async-balance-fetcher:
    build: .
    container_name: async_balance_fetcher
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    command: python main.py
